### ISSUE TITLE
Don't working with last groovy version (2.4)

### ISSUE THREAD

**Issue by danilychen** [ivnik/telnet-groovysh#2]

**Comment by ivnik** [comment]
https://github.com/ivnik/telnet-groovysh/commit/ad85df8f1b10a80aa78f383c9fd056020913855c

**Comment by danilychen** [comment]
dependency required:
<jline-version>2.12.1</jline-version>
               <dependency>
			<groupId>jline</groupId>
			<artifactId>jline</artifactId>
			<version>${jline-version}</version>
		</dependency>

**Comment by danilychen** [comment]
error while using "context" variable, but when change to "ctx" all works fine


Groovy Shell (2.4.3, JVM: 1.8.0_45)
Type ':help' or ':h' for help.

FATAL: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast
 object 'Root WebApplicationContext: startup date [Wed May 20 16:52:00 MSK 2015]
; root of context hierarchy' with class 'org.springframework.web.context.support
.XmlWebApplicationContext' to class 'groovy.lang.Binding'
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object
 'Root WebApplicationContext: startup date [Wed May 20 16:52:00 MSK 2015]; root
of context hierarchy' with class 'org.springframework.web.context.support.XmlWeb
ApplicationContext' to class 'groovy.lang.Binding'
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.co
ntinueCastOnSAM(DefaultTypeTransformation.java:402)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.co
ntinueCastOnNumber(DefaultTypeTransformation.java:316)
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.ca
stToType(DefaultTypeTransformation.java:229)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBy
tecodeAdapter.java:601)
        at org.codehaus.groovy.tools.shell.Interpreter.getContext(Interpreter.gr
oovy:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMetho
dMetaProperty.getProperty(MethodMetaProperty.java:73)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.cal
lGetProperty(GetEffectivePogoPropertySite.java:45)
        at org.codehaus.groovy.tools.shell.CommandSupport.getBinding(CommandSupp
ort.groovy:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1844)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3734)
        at org.codehaus.groovy.tools.shell.CommandSupport.getProperty(CommandSup
port.groovy)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(
PogoGetPropertySite.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjec
tGetProperty(AbstractCallSite.java:304)
        at org.codehaus.groovy.tools.shell.commands.InspectCommand.createComplet
ers(InspectCommand.groovy:50)
        at org.codehaus.groovy.tools.shell.CommandSupport.getCompleter(CommandSu
pport.groovy:134)
        at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1844)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3734)
        at org.codehaus.groovy.tools.shell.CommandSupport.getProperty(CommandSup
port.groovy)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(
PogoGetPropertySite.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty
(AbstractCallSite.java:293)
        at org.codehaus.groovy.tools.shell.CommandsMultiCompleter.add(Interactiv
eShellRunner.groovy:167)
        at org.codehaus.groovy.tools.shell.CommandsMultiCompleter$add.call(Unkno
wn Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSi
teArray.java:45)
        at org.codehaus.groovy.tools.shell.CommandsMultiCompleter$add.call(Unkno
wn Source)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(Interactiv
eShellRunner.groovy:74)
        at java_lang_Runnable$run.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.Groovysh.run(Groovysh.groovy:585)
        at ru.ind.tgs.GroovyShellService$GroovyShellServer$1.run(GroovyShellServ
ice.java:125)


Подключение к узлу утеряно.

Нажмите любую клавишу...

**Comment by danilychen** [comment]
should remove import keyword:


here is removed:
private static final List<String> DEFAULT_IMPORTS = Arrays.asList(
            "java.util.*",
            "static java.util.concurrent.TimeUnit.*"

**Comment by ivnik** [comment]
fixed, https://github.com/ivnik/telnet-groovysh/commit/ba8b12bead91e5e4ee52ba7a5f99b8ea90b4ab4d
